#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 2080adc7-e590-45a6-bb5d-230e23125231
# Source File: Start.psf
#------------------------------------------------------------------------
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
8AIAAB+LCAAAAAAABABlksuuokAURecm/oO5U5NG5aEkXpMCRC2weAgizlBB3lVSyOvr27496aTP
6OTs7DNYWWs7vOMmrHolqIPJZ6EJLr+/2F/zr814NJmsjSp5JmWQq0keoqAIN6c6qOpfhEZr5r/s
p6HiqthktSTOq+2wt54AyIYig78jAQW587nZpsCNnKgzB1u8YKVzLKirstthcjiuHups0bnVxX0L
DikYFgtIApCOR8j1Zx6PF00QlSJcOgw2WakStNI8DrFZXcErz2TLpJDsZGrCbXgCU0zJoVfATb/Y
uJ8dhkzaniMkf77NkW5a1PBf51R+bg0Kd1uvoFaIGa6GqtEBZdkaMXta5XX9Fh/YerG3lkscVzEY
wUQ0NbtL/9SIwEjWeHSXXTVhpIDEvpB5B+gmLs/J0GsbFz57GoBMVAWkLeKw2zVLTHTfDBNLbo8i
PJLrM8Yr+XwaVnOM+Ho88l5pWP+ByH4gNuRFbmfH03I3aQf2JDARujxC1PlZfxRXzjsShZKw7py8
ed7mQk9k2LOtmso01Sp7MR41XZ5ytpFDT9nfilgXB9JX6HyLge+rfPpWLYs1D+D8KHCRyS2orpxh
6agCSHnoaRX2GgeL+5E0KnmNR2Wspcmr0/azi9jKrj6oeNhl2wKCJy4XaM/3eya9gFs77dwSFoJP
30bz6Bo29LtnXCCfwnvuyBw0+WQ80mBiLWCp7cAyJxCrvL3aE3bZczCWmMTirknpyz537aypQpfm
3Sv6IouOqlxRP7Znh49U32vmR7of/QClYXHLk5BOmM9lzfxr+OY3i85dvfACAAA=#>
#endregion

<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2020 v5.7.172
     Generated on:       9/8/2021 9:42 PM
     Generated by:       Suhail Yuli
    --------------------------------------------------------------------------------
    .DESCRIPTION
        GUI script generated by PowerShell Studio 2020
#>


#----------------------------------------------
#region Application Functions
#----------------------------------------------

#endregion Application Functions

#----------------------------------------------
# Generated Form Function
#----------------------------------------------
function Show-Start_psf {

	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$form1 = New-Object 'System.Windows.Forms.Form'
	$tabcontrol1 = New-Object 'System.Windows.Forms.TabControl'
	$tabpage1 = New-Object 'System.Windows.Forms.TabPage'
	$tabpage2 = New-Object 'System.Windows.Forms.TabPage'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$form1_Load={
		#TODO: Initialize Form Controls here
		
	}
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$form1.WindowState = $InitialFormWindowState
	}
	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$form1.remove_Load($form1_Load)
			$form1.remove_Load($Form_StateCorrection_Load)
			$form1.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$form1.SuspendLayout()
	$tabcontrol1.SuspendLayout()
	#
	# form1
	#
	$form1.Controls.Add($tabcontrol1)
	$form1.AutoScaleDimensions = '6, 13'
	$form1.AutoScaleMode = 'Font'
	$form1.ClientSize = '284, 261'
	$form1.Name = 'form1'
	$form1.Text = 'Form'
	$form1.add_Load($form1_Load)
	#
	# tabcontrol1
	#
	$tabcontrol1.Controls.Add($tabpage1)
	$tabcontrol1.Controls.Add($tabpage2)
	$tabcontrol1.Location = '13, 1'
	$tabcontrol1.Name = 'tabcontrol1'
	$tabcontrol1.SelectedIndex = 0
	$tabcontrol1.Size = '259, 248'
	$tabcontrol1.TabIndex = 0
	#
	# tabpage1
	#
	$tabpage1.Location = '4, 22'
	$tabpage1.Name = 'tabpage1'
	$tabpage1.Padding = '3, 3, 3, 3'
	$tabpage1.Size = '251, 222'
	$tabpage1.TabIndex = 0
	$tabpage1.Text = 'tabpage1'
	$tabpage1.UseVisualStyleBackColor = $True
	#
	# tabpage2
	#
	$tabpage2.Location = '4, 22'
	$tabpage2.Name = 'tabpage2'
	$tabpage2.Padding = '3, 3, 3, 3'
	$tabpage2.Size = '251, 222'
	$tabpage2.TabIndex = 1
	$tabpage2.Text = 'tabpage2'
	$tabpage2.UseVisualStyleBackColor = $True
	$tabcontrol1.ResumeLayout()
	$form1.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $form1.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$form1.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$form1.add_FormClosed($Form_Cleanup_FormClosed)
	#Show the Form
	return $form1.ShowDialog()

} #End Function

#Call the form
Show-Start_psf | Out-Null
